language: elixir

otp_release:
  - 17.0
  - 17.1
  - 17.3
  - 18.0
  - 18.1
  - 18.2
  - 18.3
  - 19

elixir:
  - 1.0
  - 1.1
  - 1.2
  - 1.3

sudo: false

env:
  global:
    - MIX_ENV=test
    - HEX_UNSAFE_HTTPS=1

